<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Replicate Specht et al. 2019 mass spectrometry-based single-cell proteomics analysis • SCoPE2.replication</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Replicate Specht et al. 2019 mass spectrometry-based single-cell proteomics analysis">
<meta property="og:description" content="SCoPE2.replication">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">SCoPE2.replication</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/SCoPE2.html">Replicate Specht et al. 2019 mass spectrometry-based single-cell proteomics analysis</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="SCoPE2_files/header-attrs-2.6/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Replicate Specht et al. 2019 mass spectrometry-based single-cell proteomics analysis</h1>
                        <h4 class="author">Christophe Vanderaa<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>, Computational Biology, UCLouvain</h4>
                        <h4 class="author">Laurent Gatto, Computational Biology, UCLouvain</h4>
            
            <h4 class="date">18 February 2021</h4>
      
      
      <div class="hidden name"><code>SCoPE2.Rmd</code></div>

    </div>

    
        <div class="abstract">
      <p class="abstract">Abstract</p>
      Recent advances in sample preparation, processing and mass spectrometry (MS) have allowed the emergence of MS-based single-cell proteomics (SCP). This vignette presents a robust and standardized workflow to reproduce the data analysis of SCoPE2, one of the pioneering works in the field developed by the Slavov Lab. The implementation uses well-defined Bioconductor classes that provide powerful tools for single-cell RNA sequencing and for shotgun proteomics. We demonstrate that our pipeline can reproduce the SCoPE2 analysis using only a few lines of code.
    </div>
    
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>SCoPE2 (<span class="citation">Specht et al. (2019)</span>) is the first mass spectrometry (MS)-based single cell proteomics (SCP) protocol that has been used to profile thousands of proteins in thousands of cells. This is a technical milestone for SCP and it opens the door for fine-grain understanding of biological processes within and between cells at the protein level. The emergence of SCP data leads to the need of new computational developments that can deal with the specificities and challenges of this new type of data.</p>
<p>Although the authors provided all code and data required for fully reproducing their analysis, the code is difficult to read, implements many functions from scratch, and is based on generic table formats not suited for easy SCP data manipulation. This makes their workflow difficult to re-use for other analyses. Our goal is to bridge the gap between data acquisition and data interpretation by providing a new computational framework that is tailored for MS-SCP data. The SCoPE2 dataset is an ideal dataset to showcase its robustness and its ease of use.</p>
<p>Let’s first load the replication package to make use of some helper functions.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"SCoPE2.replication"</span><span class="op">)</span></code></pre></div>
<pre><code>## Loading required package: SingleCellExperiment</code></pre>
<pre><code>## Loading required package: SummarizedExperiment</code></pre>
<pre><code>## Loading required package: MatrixGenerics</code></pre>
<pre><code>## Loading required package: matrixStats</code></pre>
<pre><code>## 
## Attaching package: 'MatrixGenerics'</code></pre>
<pre><code>## The following objects are masked from 'package:matrixStats':
## 
##     colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
##     colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
##     colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
##     colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
##     colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
##     colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
##     colWeightedMeans, colWeightedMedians, colWeightedSds,
##     colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
##     rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
##     rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
##     rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
##     rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
##     rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
##     rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
##     rowWeightedSds, rowWeightedVars</code></pre>
<pre><code>## Loading required package: GenomicRanges</code></pre>
<pre><code>## Loading required package: stats4</code></pre>
<pre><code>## Loading required package: BiocGenerics</code></pre>
<pre><code>## Loading required package: parallel</code></pre>
<pre><code>## 
## Attaching package: 'BiocGenerics'</code></pre>
<pre><code>## The following objects are masked from 'package:parallel':
## 
##     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
##     clusterExport, clusterMap, parApply, parCapply, parLapply,
##     parLapplyLB, parRapply, parSapply, parSapplyLB</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     IQR, mad, sd, var, xtabs</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     anyDuplicated, append, as.data.frame, basename, cbind, colnames,
##     dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
##     grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
##     order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
##     rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
##     union, unique, unsplit, which.max, which.min</code></pre>
<pre><code>## Loading required package: S4Vectors</code></pre>
<pre><code>## 
## Attaching package: 'S4Vectors'</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     expand.grid, I, unname</code></pre>
<pre><code>## Loading required package: IRanges</code></pre>
<pre><code>## Loading required package: GenomeInfoDb</code></pre>
<pre><code>## Loading required package: Biobase</code></pre>
<pre><code>## Welcome to Bioconductor
## 
##     Vignettes contain introductory material; view with
##     'browseVignettes()'. To cite Bioconductor, see
##     'citation("Biobase")', and for packages 'citation("pkgname")'.</code></pre>
<pre><code>## 
## Attaching package: 'Biobase'</code></pre>
<pre><code>## The following object is masked from 'package:MatrixGenerics':
## 
##     rowMedians</code></pre>
<pre><code>## The following objects are masked from 'package:matrixStats':
## 
##     anyMissing, rowMedians</code></pre>
<pre><code>## Loading required package: QFeatures</code></pre>
<pre><code>## Loading required package: MultiAssayExperiment</code></pre>
<pre><code>## 
## Attaching package: 'QFeatures'</code></pre>
<pre><code>## The following object is masked from 'package:MultiAssayExperiment':
## 
##     longFormat</code></pre>
<pre><code>## The following object is masked from 'package:base':
## 
##     sweep</code></pre>
<pre><code>## Loading required package: scp</code></pre>
<pre><code>## Loading required package: scpdata</code></pre>
<pre><code>## Loading required package: ExperimentHub</code></pre>
<pre><code>## Loading required package: AnnotationHub</code></pre>
<pre><code>## Loading required package: BiocFileCache</code></pre>
<pre><code>## Loading required package: dbplyr</code></pre>
<pre><code>## 
## Attaching package: 'AnnotationHub'</code></pre>
<pre><code>## The following object is masked from 'package:Biobase':
## 
##     cache</code></pre>
<pre><code>## snapshotDate(): 2021-02-11</code></pre>
<pre><code>## 
## This is scpdata version 0.99.2.
## Use 'scpdata()' to list available data sets.</code></pre>
<div id="data-framework-and-scp" class="section level3">
<h3 class="hasAnchor">
<a href="#data-framework-and-scp" class="anchor"></a>Data framework and <code>scp</code>
</h3>
<p>Our first contribution is the development of a new data framework that combines two existing Bioconductor classes: the <code>SingleCellExperiment</code> that provides an interface to many cutting edge methods for single-cell analysis and <code>QFeatures</code> that facilitates manipulation and processing of MS-based quantitative data. See the <a href="http://www.bioconductor.org/packages/release/bioc/vignettes/scp/inst/doc/scp.html"><code>scp</code> vignette</a> for more detailed information about the data structure. The <code>scp</code> package provides functionality for manipulating this MS-SCP data structure. <code>scp</code> is an extension to the <code>QFeatures</code> package. The emphasis is put on the standardization and the thorough documentation of the functions in order to (i) facilitate analysis for non-experts, (ii) provide an efficient environment for processing (large) MS-SCP data sets, (iii) be compatible for both multiplexed and label free quantification, the two main protocols for MS-SCP and (iv) facilitate the inclusion of external methods for promoting continuous improvement of the MS-SCP data analyses.</p>
<p>The required packages for running this workflow are listed below.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Core packages of this workflow</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">SingleCellExperiment</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/RforMassSpectrometry/QFeatures">QFeatures</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">scpdata</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://UCLouvain-CBIO.github.io/scp">scp</a></span><span class="op">)</span>
<span class="co">## Utility packages for data manipulation and visualization</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></code></pre></div>
</div>
<div id="scpdata-and-the-scope2-dataset" class="section level3">
<h3 class="hasAnchor">
<a href="#scpdata-and-the-scope2-dataset" class="anchor"></a><code>scpdata</code> and the SCoPE2 dataset</h3>
<p>We also implemented a data package called <code>scpdata</code>. It distributes published MS-SCP datasets, such as the SCoPE2 dataset. The datasets were downloaded from the data source provided in the publication and formatted to a <code>QFeatures</code> object so that it is compatible with our software. The underlying data storage is based on the <code>ExperimentHub</code> package that provides a cloud-based storage infrastructure.</p>
<p>The SCoPE2 dataset (<span class="citation">Specht et al. (2019)</span>) is provided at different levels of processing:</p>
<ul>
<li>The <strong>raw data</strong> files that were generated by the mass-spectrometer software.</li>
<li>A <strong>PSM data</strong> table obtained from the MaxQuant software that performs spectrum identification and quantification. The provided table was further processed using DART-ID (<span class="citation">Chen, Franks, and Slavov (2019)</span>) to improve the identification rate.</li>
<li>A <strong>peptide data</strong> table obtained from the SCoPE2 analysis script.</li>
<li>A <strong>protein data</strong> table obtained as the final table from the SCoPE2 analysis script.</li>
</ul>
<p>The workflow starts with the PSM table and will generate the peptide and the protein data. The authors provided the PSM dataset as a data table (<code>data.frame</code>). The files can be downloaded from SCoPE2 repository of the Slavov Lab <a href="http://scope2.slavovlab.net/">website</a>. The formatted SCoPE2 dataset can be retrieved from the <code>scpdata</code> package with the <code><a href="https://rdrr.io/pkg/scpdata/man/specht2019v3.html">specht2019v3()</a></code> function. Note that <code>v3</code> stands for the third version release of the data in October 2020.</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/scpdata/man/specht2019v3.html">specht2019v3</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## snapshotDate(): 2021-02-11</code></pre>
<pre><code>## see ?scpdata and browseVignettes('scpdata') for documentation</code></pre>
<pre><code>## loading from cache</code></pre>
<p>The data contain 179 different <code>SingleCellExperiment</code> objects that we refer to as <strong>assays</strong>. Each assay contains expression data along with feature metadata. Below, we show the overview of the <code>scp</code> dataset.</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span></code></pre></div>
<pre><code>## An instance of class QFeatures containing 179 assays:
##  [1] 190222S_LCA9_X_FP94AA: SingleCellExperiment with 2777 rows and 11 columns 
##  [2] 190222S_LCA9_X_FP94AB: SingleCellExperiment with 4348 rows and 11 columns 
##  [3] 190222S_LCA9_X_FP94AC: SingleCellExperiment with 4917 rows and 11 columns 
##  ...
##  [177] 191110S_LCB7_X_APNOV16plex2_Set_9: SingleCellExperiment with 4934 rows and 16 columns 
##  [178] peptides: SingleCellExperiment with 9354 rows and 1490 columns 
##  [179] proteins: SingleCellExperiment with 3042 rows and 1490 columns</code></pre>
<p>177 out of the 179 assays are PSM data, each assay corresponding to a separate MS run. 63 contain 11 columns and 114 contain 16 columns. This is because the SCoPE2 protocol first included TMT-11 multiplexing, but soon the TMT-16 multiplexing was released and the authors decided to switch to the latter to increase the throughput of the technique. Notice that the assays were also acquired in 4 chromatographic batches. Here is an overview of the distribution of the assays across the TMT and chromatographic batches.</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">colData</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="fu">select</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">Set</span>, <span class="va">lcbatch</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">unique</span> <span class="op">%&gt;%</span>
    <span class="fu">mutate</span><span class="op">(</span>TMT <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span><span class="st">"16plex"</span>, <span class="va">Set</span><span class="op">)</span>, <span class="st">"TMT16"</span>, <span class="st">"TMT11"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">lcbatch</span>,
        fill <span class="op">=</span> <span class="va">TMT</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"count"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"Chromatographic batch"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: Ignoring unknown parameters: binwidth, bins, pad</code></pre>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-4-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>The dataset also contains a <code>peptides</code> assay and a <code>proteins</code> assay that hold peptide and protein level information, respectively. The objective of this vignette is to produce the <code>peptides</code> and <code>proteins</code> assays from the 177 PSM assays following the same procedure as the SCoPE2 script but using standardized functionalities.</p>
<p>We extract the <code>peptides</code> and <code>proteins</code> assays and keep them for later benchmarking. Using double brackets <code>[[...]]</code> extracts the desired assay as a <code>SingleCellExperiment</code> object. On the other hand, using simple brackets <code>[row, col, assay]</code> subsets the desired elements/assays but preserves the <code>QFeatures</code> data structure.</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">peptides_SCoPE2</span> <span class="op">&lt;-</span> <span class="va">scp</span><span class="op">[[</span><span class="st">"peptides"</span><span class="op">]</span><span class="op">]</span>
<span class="va">proteins_SCoPE2</span> <span class="op">&lt;-</span> <span class="va">scp</span><span class="op">[[</span><span class="st">"proteins"</span><span class="op">]</span><span class="op">]</span>
<span class="va">scp</span> <span class="op">&lt;-</span> <span class="va">scp</span><span class="op">[</span>, , <span class="op">-</span><span class="op">(</span><span class="fl">178</span><span class="op">:</span><span class="fl">179</span><span class="op">)</span><span class="op">]</span></code></pre></div>
<pre><code>## Warning: 'experiments' dropped; see 'metadata'</code></pre>
<pre><code>## harmonizing input:
##   removing 2980 sampleMap rows not in names(experiments)</code></pre>
<p>To avoid confusions during later benchmarking of the replication, we name the peptide and protein data sets generated by the SCoPE2 script <code>peptides_SCoPE2</code> and <code>proteins_SCoPE2</code>, respectively.</p>
</div>
<div id="the-scope2-workflow" class="section level2">
<h2 class="hasAnchor">
<a href="#the-scope2-workflow" class="anchor"></a>The SCoPE2 workflow</h2>
<p>We here give a schematic overview of the different processing steps performed by the SCoPE2 script. The r</p>
<div class="figure" style="text-align: center">
<img src="figs/workflow.png" alt="Overview of the SCoPE2 workflow." width="100%"><p class="caption">
Overview of the SCoPE2 workflow.
</p>
</div>
<p>The SCoPE2 code provided along with the article can be retrieved from <a href="https://github.com/SlavovLab/SCoPE2/blob/master/code/SCoPE2_analysis.R">this GitHub repository</a>. Note that we here used the part of the script that performs the stringent feature selection (see the original paper for more details).</p>
<p>The objective of this vignette is to replicate the SCoPE2 script while providing standardized, easy-to-read, and well documented code. We will demonstrate the success of the replication with a little benchmarking of our results against the data provided by the authors. Finally, we will perform some further data exploration to highlight the remaining challenges that still require to be tackled in MS-based SCP.</p>
</div>
</div>
<div id="filter-the-psm-data" class="section level1">
<h1 class="hasAnchor">
<a href="#filter-the-psm-data" class="anchor"></a>Filter the PSM data</h1>
<p>The SCoPE2 analysis starts with filtering low-confidence PSMs. Each PSM assay contains feature meta-information that are stored in the assay <code>rowData</code>. The <code>QFeatures</code> package allows to quickly filter the rows of an assay by using these information. The available variables in the <code>rowData</code> are listed below for each assay.</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-class.html">rowDataNames</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span></code></pre></div>
<pre><code>## CharacterList of length 177
## [["190222S_LCA9_X_FP94AA"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AB"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AC"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AD"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AE"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AF"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AG"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AH"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AI"]] uid Sequence Length ... digest modseq peptide
## [["190222S_LCA9_X_FP94AJ"]] uid Sequence Length ... digest modseq peptide
## ...
## &lt;167 more elements&gt;</code></pre>
<div id="filter-out-failed-runs-based-on-psm-content" class="section level2">
<h2 class="hasAnchor">
<a href="#filter-out-failed-runs-based-on-psm-content" class="anchor"></a>Filter out failed runs based on PSM content</h2>
<p>First, only the assays that have sufficient PSMs are kept. The authors keep an assay if it has over 500 PSMs. Before filtering, let’s first look at the distribution of the number of PSMs per assay. Note that we can easily extract the number of rows (here PSMs) and the number of columns (TMT channels) of each assay using the <code>dims</code> function implemented in <code>QFeatures</code>.</p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nPSMs</span> <span class="op">&lt;-</span> <span class="fu">dims</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span>, <span class="op">]</span></code></pre></div>
<p>Let’s have a look at the number of features that were identified in the different runs.</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">nPSMs</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">nPSMs</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fl">500</span><span class="op">)</span></code></pre></div>
<p><img src="SCoPE2_files/figure-html/plot_dims-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>4 assays have very few number of PSMs, probably because those runs failed. They are hence below the threshold of 500 and are removed from the analysis. To perform this, we take advantage of the subsetting method of a <code>QFeatures</code> object. It can be seen as a three-order array: <span class="math inline">\(features \times samples \times assay\)</span>. Hence, <code>QFeatures</code> supports three-order subsetting <code>x[rows, columns, assays]</code>.</p>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="va">scp</span><span class="op">[</span>, , <span class="va">nPSMs</span> <span class="op">&gt;</span> <span class="fl">500</span><span class="op">]</span></code></pre></div>
<pre><code>## Warning: 'experiments' dropped; see 'metadata'</code></pre>
<pre><code>## harmonizing input:
##   removing 59 sampleMap rows not in names(experiments)
##   removing 59 colData rownames not in sampleMap 'primary'</code></pre>
<p>You may notice that a warning is thrown when performing the subsetting step. This is because, as we expected, a few assays were dropped. We can find them back in the <code>metadata</code> slot:</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">metadata</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span></code></pre></div>
<pre><code>## $drops.experiments
## [1] "peptides"                          "proteins"                         
## [3] "190222S_LCA9_X_FP94BD"             "191026S_LCB7_X_AP16plex_Set_15"   
## [5] "191108S_LCB7_X_APNOV16plex_Set_24" "191108S_LCB7_X_APNOV16plex_Set_29"</code></pre>
</div>
<div id="filter-out-psms-with-high-false-discovery-rate" class="section level2">
<h2 class="hasAnchor">
<a href="#filter-out-psms-with-high-false-discovery-rate" class="anchor"></a>Filter out PSMs with high false discovery rate</h2>
<p>Next, SCoPE2 filters PSMs based on the false discovery rate (FDR) for identification. As mentioned in the introduction, the PSM data were already processed with DART-ID (<span class="citation">Chen, Franks, and Slavov (2019)</span>), a python software that updates the confidence in peptide identification using an Bayesian inference approach. DART-ID outputs for every PSM the updated posterior error probability (PEP). Filtering on the PEP is too conservative and it is rather advised to filter based on FDR (<span class="citation">Käll et al. (2008)</span>). To control for the FDR, we need to compute q-values, that correspond to the minimal FDR threshold that would still select the associated feature.</p>
<p>We can easily compute q-values from the PEPs computed by MaxQuant or updated by DART-ID using the <code>pep2qvalue</code> function. In the SCoPE workflow, the features are selected based on the FDR at PSM level and at protein level. The PEP information (<code>dart_PEP</code>) as well as the protein information (<code>protein</code>) are retrieved from the <code>rowData</code> of each assay. The function will store the computed q-values in the <code>rowData</code> and we give the name of <code>qvalue_psm</code> and <code>qvalue_protein</code> for the PSM and proteins q-values, respectively.</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/pep2qvalue.html">pep2qvalue</a></span><span class="op">(</span><span class="va">scp</span>,
                  i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span>,
                  PEP <span class="op">=</span> <span class="st">"dart_PEP"</span>,
                  rowDataName <span class="op">=</span> <span class="st">"qvalue_psm"</span><span class="op">)</span>
<span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/pep2qvalue.html">pep2qvalue</a></span><span class="op">(</span><span class="va">scp</span>,
                  i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span>,
                  groupBy <span class="op">=</span> <span class="st">"protein"</span>,
                  PEP <span class="op">=</span> <span class="st">"dart_PEP"</span>,
                  rowDataName <span class="op">=</span> <span class="st">"qvalue_protein"</span><span class="op">)</span></code></pre></div>
<p>We can extract the q-values from the <code>rowData</code> of several assays using the <code>rowDataToDF</code> function. It takes the <code>rowData</code> of interest and returns a single <code>DataFrame</code> table with variables of interest. We plot the q-values along with the DART-ID PEPs using <code>ggplot2</code> facets.</p>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/rowDataToDF.html">rowDataToDF</a></span><span class="op">(</span><span class="va">scp</span>,
            i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span>,
            vars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dart_PEP"</span>, <span class="st">"qvalue_psm"</span>, <span class="st">"qvalue_protein"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="fu">pivot_longer</span><span class="op">(</span>cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dart_PEP"</span>, <span class="st">"qvalue_psm"</span>, <span class="st">"qvalue_protein"</span><span class="op">)</span>,
                 names_to <span class="op">=</span> <span class="st">"measure"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_x_log10</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">facet_grid</span><span class="op">(</span>rows <span class="op">=</span> <span class="fu">vars</span><span class="op">(</span><span class="va">measure</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: Transformation introduced infinite values in continuous x-axis</code></pre>
<pre><code>## Warning: Removed 6690 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-8-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>We filter the PSMs to control for a 1% PSM and protein FDR. We can easily perform this on our <code>QFeatures</code> object by using the <code>filterFeatures</code> function. The q-values are directly accessed from the <code>rowData</code> of each assay.</p>
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-filtering.html">filterFeatures</a></span><span class="op">(</span><span class="va">scp</span>,
                      <span class="op">~</span> <span class="va">qvalue_psm</span> <span class="op">&lt;</span> <span class="fl">0.01</span> <span class="op">&amp;</span> <span class="va">qvalue_protein</span> <span class="op">&lt;</span> <span class="fl">0.01</span><span class="op">)</span></code></pre></div>
</div>
<div id="filter-out-contaminants" class="section level2">
<h2 class="hasAnchor">
<a href="#filter-out-contaminants" class="anchor"></a>Filter out contaminants</h2>
<p>We will now remove PSMs that were matched to contaminant proteins (the protein name starts with <code>CON</code>) or to the decoy database (the protein name starts with <code>REV</code>). Again, <code>filterFeatures</code> can directly access the protein names from the <code>rowData</code>.</p>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-filtering.html">filterFeatures</a></span><span class="op">(</span><span class="va">scp</span>,
                      <span class="op">~</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span><span class="st">"REV|CON"</span>, <span class="va">protein</span><span class="op">)</span><span class="op">)</span></code></pre></div>
</div>
<div id="filter-out-noisy-spectra" class="section level2">
<h2 class="hasAnchor">
<a href="#filter-out-noisy-spectra" class="anchor"></a>Filter out noisy spectra</h2>
<p>A PIF (parental ion fraction) smaller than 80 % indicates the associated spectra is contaminated by co-isolated peptides and therefore the quantification becomes unreliable. The PIF was computed by MaxQuant and is readily available for filtering.</p>
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-filtering.html">filterFeatures</a></span><span class="op">(</span><span class="va">scp</span>,
                      <span class="op">~</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">PIF</span><span class="op">)</span> <span class="op">&amp;</span> <span class="va">PIF</span> <span class="op">&gt;</span> <span class="fl">0.8</span><span class="op">)</span></code></pre></div>
</div>
<div id="filter-out-psms-with-high-sample-to-carrier-ratio" class="section level2">
<h2 class="hasAnchor">
<a href="#filter-out-psms-with-high-sample-to-carrier-ratio" class="anchor"></a>Filter out PSMs with high sample to carrier ratio</h2>
<p>The PSMs are next filtered based on the sample to carrier ratio (SCR), that is the reporter ion intensity of a single-cell sample divided by the reporter ion intensity of the carrier (200 cells) acquired during the same run as the sample. It is expected that the carrier intensities are much higher than the single-cell intensities. We implemented the <code>computeSCR</code> function that computes the SCR for each PSM averaged over all samples of interest in a given assay. A PSM is removed when the mean SCR exceeds 10 %. To perform this, we need to tell the function which columns are the samples of interest and which is the carrier. The <code>colData</code> of the <code>QFeatures</code> object is used to define this.</p>
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">scp</span><span class="op">$</span><span class="va">SampleType</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##      Blank    Carrier Macrophage   Monocyte  Reference     Unused 
##        168        173       1198        462        173        284</code></pre>
<p>In this dataset, <code>SampleType</code> gives the type of sample that is present in each TMT channel. The SCoPE2 protocol includes 5 types of samples: * The carrier channels (<code>Carrier</code>) contain 200 cell equivalents and are meant to boost the peptide identification rate. * The normalization channels (<code>Reference</code>) contain 5 cell equivalents and are used to partially correct for between-run variation. * The unused channels (<code>Unused</code>) are channels that are left empty due to isotopic cross-contamination by the carrier channel. * The blank channels (<code>Blank</code>) contain samples that do not contain any cell but are processed as single-cell samples. * The single-cell sample channels contain the single-cell samples of interest (<code>Macrophage</code> or <code>Monocyte</code>).</p>
<p>The <code>computeSCR</code> function expects the user to provide a pattern (following regular expression syntax) that uniquely identifies a carrier channel in each run and the samples or blanks. The function will store the mean SCR of each feature in the <code>rowData</code> of each assay.</p>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/computeSCR.html">computeSCR</a></span><span class="op">(</span><span class="va">scp</span>,
                  i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span>,
                  colDataCol <span class="op">=</span> <span class="st">"SampleType"</span>,
                  carrierPattern <span class="op">=</span> <span class="st">"Carrier"</span>,
                  samplePattern <span class="op">=</span> <span class="fl">4</span><span class="op">:</span><span class="fl">16</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning in computeSCR(scp, i = names(scp), colDataCol = "SampleType",
## carrierPattern = "Carrier", : The pattern is numeric. This is only allowed for
## replicating the SCoPE2 analysis and will later get defunct.</code></pre>
<p>Before applying the filter, we plot the distribution of the mean SCR.</p>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/rowDataToDF.html">rowDataToDF</a></span><span class="op">(</span><span class="va">scp</span>,
            i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span>,
            vars <span class="op">=</span> <span class="st">"MeanSCR"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">MeanSCR</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">200</span>, <span class="fl">0.1</span><span class="op">)</span>,
               lty <span class="op">=</span> <span class="fl">2</span><span class="op">:</span><span class="fl">1</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_x_log10</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-10-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>A great majority of the PSMs have a mean SCR that is lower than 10%, as expected. Interestingly, the mode of the distribution is located at ~1%. This is expected since every sample channel contains a single-cell and the carrier contains 200 cells leading to an expected ratio of 0.5% (dashed line). We remove the PSMs for which the mean SCR exceeds the 10% threshold.</p>
<div class="sourceCode" id="cb74"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-filtering.html">filterFeatures</a></span><span class="op">(</span><span class="va">scp</span>,
                      <span class="op">~</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">MeanSCR</span><span class="op">)</span> <span class="op">&amp;</span>
                          <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/is.finite.html">is.infinite</a></span><span class="op">(</span><span class="va">MeanSCR</span><span class="op">)</span> <span class="op">&amp;</span>
                          <span class="va">MeanSCR</span> <span class="op">&lt;</span> <span class="fl">0.1</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="normalize-to-reference" class="section level1">
<h1 class="hasAnchor">
<a href="#normalize-to-reference" class="anchor"></a>Normalize to reference</h1>
<p>In order to partially correct for between-run variation, SCoPE2 computes relative reporter ion intensities. This means that intensities measured for single-cells are divided by the reference channel containing 5-cell equivalents. We use the <code>divideByReference</code> function that divides channels of interest by the reference channel. Similarly to <code>computeSCR</code>, we can point to the samples and the reference columns in each assay using the annotation contained in the <code>colData</code>. We will here divide all columns (using the regular expression wildcard <code>.</code>) by the reference channel (<code>Reference</code>). Notice that when taking all samples we also include the reference channel. Hence, from now on, the reference channels will contain only <code>1</code>s.</p>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/divideByReference.html">divideByReference</a></span><span class="op">(</span><span class="va">scp</span>,
                         i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span>,
                         colDataCol <span class="op">=</span> <span class="st">"SampleType"</span>,
                         samplePattern <span class="op">=</span> <span class="st">"."</span>,
                         refPattern <span class="op">=</span> <span class="st">"Reference"</span><span class="op">)</span></code></pre></div>
</div>
<div id="aggregate-psm-data-to-peptide-data" class="section level1">
<h1 class="hasAnchor">
<a href="#aggregate-psm-data-to-peptide-data" class="anchor"></a>Aggregate PSM data to peptide data</h1>
<p>Now that the PSM assays are processed, we can aggregate them to peptides. This is performed using the <code>aggregateFeaturesOverAssays</code> function. This is a wrapper function in <code>scp</code> that sequentially calls the <code>aggregateFeatures</code> from the <code>QFeatures</code> package over the different assays. For each assay, the function aggregates several PSMs into a unique peptide given an aggregating variable in the <code>rowData</code> (peptide sequence) and a user-supplied aggregating function (the median for instance). Regarding the aggregating function, the SCoPE2 analysis removes duplicated peptide sequences per run by taking the first non-missing value. While better alternatives are documented in <code><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-aggregate.html">QFeatures::aggregateFeatures</a></code>, we still use this approach for the sake of replication and for illustrating that custom functions can be applied.</p>
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">remove.duplicates</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span>
    <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">2</span>, <span class="kw">function</span><span class="op">(</span><span class="va">xx</span><span class="op">)</span> <span class="va">xx</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">xx</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span> <span class="op">)</span></code></pre></div>
<p>The aggregated peptide assays must be given a name. We here used the original names with <code>peptides_</code> at the start.</p>
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">peptideAssays</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"peptides_"</span>, <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>We now have all the required information to aggregate the PSMs in the different batches to peptides.</p>
<div class="sourceCode" id="cb78"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/aggregateFeaturesOverAssays.html">aggregateFeaturesOverAssays</a></span><span class="op">(</span><span class="va">scp</span>,
                                   i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span>,
                                   fcol <span class="op">=</span> <span class="st">"peptide"</span>,
                                   name <span class="op">=</span> <span class="va">peptideAssays</span>,
                                   fun <span class="op">=</span> <span class="va">remove.duplicates</span><span class="op">)</span></code></pre></div>
<p>Under the hood, the <code>QFeatures</code> architecture preserves the relationship between the aggregated assays. See <code><a href="https://rdrr.io/pkg/QFeatures/man/AssayLinks.html">?AssayLinks</a></code> for more information on relationships between assays. Notice that <code>aggregateFeaturesOverAssays</code> created as many new assays as the number of supplied assays.</p>
<div class="sourceCode" id="cb79"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span></code></pre></div>
<pre><code>## An instance of class QFeatures containing 346 assays:
##  [1] 190222S_LCA9_X_FP94AA: SingleCellExperiment with 1098 rows and 11 columns 
##  [2] 190222S_LCA9_X_FP94AB: SingleCellExperiment with 2420 rows and 11 columns 
##  [3] 190222S_LCA9_X_FP94AC: SingleCellExperiment with 2775 rows and 11 columns 
##  ...
##  [344] peptides_191110S_LCB7_X_APNOV16plex2_Set_7: SingleCellExperiment with 2379 rows and 16 columns 
##  [345] peptides_191110S_LCB7_X_APNOV16plex2_Set_8: SingleCellExperiment with 2480 rows and 16 columns 
##  [346] peptides_191110S_LCB7_X_APNOV16plex2_Set_9: SingleCellExperiment with 2308 rows and 16 columns</code></pre>
</div>
<div id="join-the-scope2-sets-in-one-assay" class="section level1">
<h1 class="hasAnchor">
<a href="#join-the-scope2-sets-in-one-assay" class="anchor"></a>Join the SCoPE2 sets in one assay</h1>
<p>Up to now, we kept the data belonging to each MS run in separate assays. We now combine all batches into a single assay. This can easily be done using the <code>joinAssays</code> function from the <code>QFeatures</code> package.</p>
<p>We however need to account for an issue. The <code>joinAssays</code> will only keep the metadata variables that have the same value between matching rows. However, some peptide sequences map to one protein in one run and to another protein in another run. Hence, the protein sequence is not constant for all peptides and is removed during joining. It is important we keep the protein sequence in the <code>rowData</code> since we will later need it to aggregate peptides to proteins. To avoid this issue, we replace the problematic peptides to protein mappings through majority vote.</p>
<div class="sourceCode" id="cb81"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/rowDataToDF.html">rowDataToDF</a></span><span class="op">(</span>i <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">173</span><span class="op">]</span>,
                vars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"peptide"</span>, <span class="st">"protein"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="fu">group_by</span><span class="op">(</span><span class="va">peptide</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## The majority vote happens here</span>
    <span class="fu">mutate</span><span class="op">(</span>protein <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">protein</span><span class="op">)</span>,
                                decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">select</span><span class="op">(</span><span class="va">peptide</span>, <span class="va">protein</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">peptide</span>, <span class="va">protein</span><span class="op">)</span><span class="op">)</span> <span class="op">-&gt;</span>
    <span class="va">ppMap</span>
<span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="va">peptideAssays</span><span class="op">)</span> <span class="op">{</span>
    <span class="va">pep</span> <span class="op">&lt;-</span> <span class="fu">rowData</span><span class="op">(</span><span class="va">scp</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">$</span><span class="va">peptide</span>
    <span class="co">## TODO: using `@` is a bad idea!! I should find a way to optimize</span>
    <span class="co">## rowData(scp[[i]])$protein &lt;- ... without using `@` (maybe</span>
    <span class="co">## contact M. Ramos)</span>
    <span class="fu">rowData</span><span class="op">(</span><span class="va">scp</span><span class="op">@</span><span class="va">ExperimentList</span><span class="op">@</span><span class="va">listData</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">$</span><span class="va">protein</span> <span class="op">&lt;-</span>
        <span class="va">ppMap</span><span class="op">$</span><span class="va">protein</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/match.html">match</a></span><span class="op">(</span><span class="va">pep</span>, <span class="va">ppMap</span><span class="op">$</span><span class="va">peptide</span><span class="op">)</span><span class="op">]</span>
<span class="op">}</span></code></pre></div>
<p>This code chunk is hard to read and is not standardized. conceptu</p>
<p><strong><span class="citation">(<strong>todo?</strong>)</span></strong> comment on this. The issue is that we are working with shared peptides… Discuss with Laurent.</p>
<p>Now that the peptides are correctly matched to proteins, we can join the assays.</p>
<div class="sourceCode" id="cb82"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/joinAssays.html">joinAssays</a></span><span class="op">(</span><span class="va">scp</span>,
                  i <span class="op">=</span> <span class="va">peptideAssays</span>,
                  name <span class="op">=</span> <span class="st">"peptides"</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: 'experiments' dropped; see 'metadata'</code></pre>
<pre><code>## harmonizing input:
##   removing 2458 sampleMap rows not in names(experiments)</code></pre>
<p><code>joinAssays</code> has created a new assay called <code>peptides</code> that combines the previously aggregated peptide assays.</p>
<div class="sourceCode" id="cb85"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span></code></pre></div>
<pre><code>## An instance of class QFeatures containing 347 assays:
##  [1] 190222S_LCA9_X_FP94AA: SingleCellExperiment with 1098 rows and 11 columns 
##  [2] 190222S_LCA9_X_FP94AB: SingleCellExperiment with 2420 rows and 11 columns 
##  [3] 190222S_LCA9_X_FP94AC: SingleCellExperiment with 2775 rows and 11 columns 
##  ...
##  [345] peptides_191110S_LCB7_X_APNOV16plex2_Set_8: SingleCellExperiment with 2480 rows and 16 columns 
##  [346] peptides_191110S_LCB7_X_APNOV16plex2_Set_9: SingleCellExperiment with 2308 rows and 16 columns 
##  [347] peptides: SingleCellExperiment with 15675 rows and 2458 columns</code></pre>
</div>
<div id="format-the-missing-data" class="section level1">
<h1 class="hasAnchor">
<a href="#format-the-missing-data" class="anchor"></a>Format the missing data</h1>
<p>SCoPE2 performs a cleaning step were zero and infinite values are replaced by NAs. The <code>infIsNA</code> and the <code>zeroIsNA</code> functions are provided by the <code>QFeatures</code> package.</p>
<div class="sourceCode" id="cb87"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-missing-data.html">infIsNA</a></span><span class="op">(</span><span class="va">scp</span>, i <span class="op">=</span> <span class="st">"peptides"</span><span class="op">)</span>
<span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-missing-data.html">zeroIsNA</a></span><span class="op">(</span><span class="va">scp</span>, i <span class="op">=</span> <span class="st">"peptides"</span><span class="op">)</span></code></pre></div>
</div>
<div id="filter-single-cells-based-on-median-cv" class="section level1">
<h1 class="hasAnchor">
<a href="#filter-single-cells-based-on-median-cv" class="anchor"></a>Filter single-cells based on median CV</h1>
<p>The SCoPE2 script proceeds with filtering the single-cell. The filtering is mainly based on the median coefficient of variation (CV) per cell. The median CV measures the consistency of quantification for a group of peptides that belong to a protein. We remove cells that exhibit high median CV over the different proteins. We compute the median CV per cell using the <code>medianCVperCell</code> function from the <code>scp</code> package. The function takes the <code>peptides_filter1</code> assay, protein and peptide information from the assay <code>rowData</code>, and the batch names in the <code>colData</code> of the <code>QFeatures</code> object. The peptide and batch information are required to perform normalization prior to the CV computation. Protein information is required since the CV are computed at the protein level.</p>
<div class="sourceCode" id="cb88"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://UCLouvain-CBIO.github.io/scp/reference/computeMedianCV_SCoPE2.html">computeMedianCV_SCoPE2</a></span><span class="op">(</span><span class="va">scp</span>,
                              i <span class="op">=</span> <span class="st">"peptides"</span>,
                              proteinCol <span class="op">=</span> <span class="st">"protein"</span>,
                              peptideCol <span class="op">=</span> <span class="st">"peptide"</span>,
                              batchCol <span class="op">=</span> <span class="st">"Set"</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning in computeMedianCV_SCoPE2(scp, i = "peptides", proteinCol = "protein", :
## This function is deprecated and is only present in the package for replicating
## the SCoPE2 analysis.</code></pre>
<div class="sourceCode" id="cb90"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># scp &lt;- medianCVperCell(scp,</span>
<span class="co">#                        i = peptideAssays,</span>
<span class="co">#                        groupBy = "protein",</span>
<span class="co">#                        nobs = 5,</span>
<span class="co">#                        na.rm = TRUE,</span>
<span class="co">#                        colDataName = "MedianCV",</span>
<span class="co">#                        norm = c("div.median", "mean"))</span></code></pre></div>
<p>The computed CVs are stored in the <code>colData</code> of the <code>peptides_filter1</code> assay and holds the median CV per cell computed using at least 5 observations (peptides). The main interest of computing the median CV per cell is to filter cells with reliable quantification. The blank samples are not expected to have reliable quantifications and hence can be used to estimate an empirical null distribution of the CV. This distribution helps defining a threshold that filters out single-cells that contain noisy quantification.</p>
<p>The sample annotation is contained in the <code>colData</code> of the <code>QFeatures</code> object. We will therefore first transfer the sample annotation from the <code>QFeatures</code> object to the <code>SingleCellExperiment</code> assay using the <code>transferColDataToAssay</code> function. We then directly extract the assay <code>colData</code> that contains all the required information for plotting.</p>
<div class="sourceCode" id="cb91"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">getWithColData</span><span class="op">(</span><span class="va">scp</span>, i <span class="op">=</span> <span class="st">"peptides"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">colData</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">SampleType</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Macrophage"</span>,  <span class="st">"Monocyte"</span>, <span class="st">"Blank"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">MedianCV</span>,
               fill <span class="op">=</span> <span class="va">SampleType</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fl">0.365</span><span class="op">)</span></code></pre></div>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-20-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>We can see that the protein quantification for single-cells are much more consistent within cells than the blank channels. A threshold of 0.4 best separates single-cells from empty channels.</p>
<p>We keep the cells that pass the median CV threshold. Furthermore, we keep macrophages and monocytes as those represent the samples of interest. Now the quality control and filtering is performed, we can remove the other channels.</p>
<p>We have already demonstrated how to remove assays from the dataset, but we can apply a similar subsetting for the samples present in the <code>colData</code>. Recall that the second entry in the <code><a href="https://rdrr.io/r/base/Extract.html">[</a></code> subsetting method is for samples.</p>
<div class="sourceCode" id="cb92"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="va">scp</span><span class="op">[</span>, <span class="va">scp</span><span class="op">$</span><span class="va">MedianCV</span> <span class="op">&lt;</span> <span class="fl">0.365</span> <span class="op">&amp;</span>
               <span class="va">scp</span><span class="op">$</span><span class="va">SampleType</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Macrophage"</span>, <span class="st">"Monocyte"</span><span class="op">)</span>, <span class="op">]</span></code></pre></div>
<pre><code>## harmonizing input:
##   removing 2 sampleMap rows with 'colname' not in colnames of experiments</code></pre>
<p><strong><span class="citation">(<strong>todo?</strong>)</span></strong> this is slow and requires optimization.</p>
<div class="sourceCode" id="cb94"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span></code></pre></div>
<pre><code>## An instance of class QFeatures containing 347 assays:
##  [1] 190222S_LCA9_X_FP94AA: SingleCellExperiment with 1098 rows and 4 columns 
##  [2] 190222S_LCA9_X_FP94AB: SingleCellExperiment with 2420 rows and 5 columns 
##  [3] 190222S_LCA9_X_FP94AC: SingleCellExperiment with 2775 rows and 6 columns 
##  ...
##  [345] peptides_191110S_LCB7_X_APNOV16plex2_Set_8: SingleCellExperiment with 2480 rows and 11 columns 
##  [346] peptides_191110S_LCB7_X_APNOV16plex2_Set_9: SingleCellExperiment with 2308 rows and 11 columns 
##  [347] peptides: SingleCellExperiment with 15675 rows and 1499 columns</code></pre>
</div>
<div id="process-the-peptide-data" class="section level1">
<h1 class="hasAnchor">
<a href="#process-the-peptide-data" class="anchor"></a>Process the peptide data</h1>
<p>In the SCoPE2 analysis, the peptide data is first transformed before it is aggregated to proteins. The transformation steps are: normalization, filter peptides based on missing data and log-transformation.</p>
<div id="normalization" class="section level2">
<h2 class="hasAnchor">
<a href="#normalization" class="anchor"></a>Normalization</h2>
<p>The columns (samples) of the peptide data are first normalized by dividing the relative intensities by the median relative intensities. Then, the rows (peptide) are normalized by dividing the relative intensities by the mean relative intensities. The normalized data is stored in a separate assay.</p>
<div class="sourceCode" id="cb96"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">%&gt;%</span>
    <span class="co">## Scale columns with median</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">sweep</a></span><span class="op">(</span>i <span class="op">=</span> <span class="st">"peptides"</span>,
          MARGIN <span class="op">=</span> <span class="fl">2</span>,
          FUN <span class="op">=</span> <span class="st">"/"</span>,
          STATS <span class="op">=</span> <span class="fu">colMedians</span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">.</span><span class="op">[[</span><span class="st">"peptides"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,
                             na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
          name <span class="op">=</span> <span class="st">"peptides_norm1"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Scale rows with mean</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">sweep</a></span><span class="op">(</span>i <span class="op">=</span> <span class="st">"peptides_norm1"</span>,
          MARGIN <span class="op">=</span> <span class="fl">1</span>,
          FUN <span class="op">=</span> <span class="st">"/"</span>,
          STATS <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowMeans</a></span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">.</span><span class="op">[[</span><span class="st">"peptides_norm1"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,
                           na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
          name <span class="op">=</span> <span class="st">"peptides_norm2"</span><span class="op">)</span> <span class="op">-&gt;</span>
    <span class="va">scp</span></code></pre></div>
</div>
<div id="remove-peptides-with-high-missing-rate" class="section level2">
<h2 class="hasAnchor">
<a href="#remove-peptides-with-high-missing-rate" class="anchor"></a>Remove peptides with high missing rate</h2>
<p>Peptides that contain many missing values are not informative. Therefore, we remove those with more than 99 % missing data. This is done using the <code>filterNA</code> function from <code>QFeatures</code>.</p>
<div class="sourceCode" id="cb97"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-missing-data.html">filterNA</a></span><span class="op">(</span><span class="va">scp</span>,
                i <span class="op">=</span> <span class="st">"peptides_norm2"</span>,
                pNA <span class="op">=</span> <span class="fl">0.99</span><span class="op">)</span></code></pre></div>
</div>
<div id="log-transformation" class="section level2">
<h2 class="hasAnchor">
<a href="#log-transformation" class="anchor"></a>Log-transformation</h2>
<p>The last processing step of the peptide data before aggregating to proteins is to log-transform the data. SCoPE2 uses a base 2 log-transformation.</p>
<div class="sourceCode" id="cb98"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">logTransform</a></span><span class="op">(</span><span class="va">scp</span>,
                    base <span class="op">=</span> <span class="fl">2</span>,
                    i <span class="op">=</span> <span class="st">"peptides_norm2"</span>,
                    name <span class="op">=</span> <span class="st">"peptides_log"</span><span class="op">)</span></code></pre></div>
</div>
<div id="the-scope2-peptide-data" class="section level2">
<h2 class="hasAnchor">
<a href="#the-scope2-peptide-data" class="anchor"></a>The SCoPE2 peptide data</h2>
<p>Before exporting the data as <code>Peptides-raw.csv</code>, the authors performed an additional normalization step. This step is however not considered in the remainder of the workflow.</p>
<div class="sourceCode" id="cb99"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">%&gt;%</span>
    <span class="co">## Center columns with median</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">sweep</a></span><span class="op">(</span>i <span class="op">=</span> <span class="st">"peptides_log"</span>,
          MARGIN <span class="op">=</span> <span class="fl">2</span>,
          FUN <span class="op">=</span> <span class="st">"-"</span>,
          STATS <span class="op">=</span> <span class="fu">colMedians</span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">.</span><span class="op">[[</span><span class="st">"peptides_log"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,
                             na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
          name <span class="op">=</span> <span class="st">"peptides_log_norm1"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Center rows with mean</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">sweep</a></span><span class="op">(</span>i <span class="op">=</span> <span class="st">"peptides_log_norm1"</span>,
          MARGIN <span class="op">=</span> <span class="fl">1</span>,
          FUN <span class="op">=</span> <span class="st">"-"</span>,
          STATS <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowMeans</a></span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">.</span><span class="op">[[</span><span class="st">"peptides_log_norm1"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,
                           na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
          name <span class="op">=</span> <span class="st">"peptides_scp"</span><span class="op">)</span> <span class="op">-&gt;</span>
    <span class="va">scp</span></code></pre></div>
<p>We names the last assay <code>peptides_scp</code>. We will contrast this data matrix to <code>peptides_SCoPE2</code> later in this vignette to assess the fidelity of the replication.</p>
</div>
</div>
<div id="aggregate-peptide-data-to-protein-data" class="section level1">
<h1 class="hasAnchor">
<a href="#aggregate-peptide-data-to-protein-data" class="anchor"></a>Aggregate peptide data to protein data</h1>
<p>Similarly to aggregating PSM data to peptide data, we can aggregate peptide data to protein data using the <code>aggregateFeatures</code> function. Note that we here use the median as a summarizing function.</p>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-aggregate.html">aggregateFeatures</a></span><span class="op">(</span><span class="va">scp</span>,
                         i <span class="op">=</span> <span class="st">"peptides_log"</span>,
                         name <span class="op">=</span> <span class="st">"proteins"</span>,
                         fcol <span class="op">=</span> <span class="st">"protein"</span>,
                         fun <span class="op">=</span> <span class="fu">matrixStats</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/matrixStats/man/rowMedians.html">colMedians</a></span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## Your quantitative and row data contain missing values. Please read the
## relevant section(s) in the aggregateFeatures manual page regarding the
## effects of missing values on data aggregation.</code></pre>
</div>
<div id="process-the-protein-data" class="section level1">
<h1 class="hasAnchor">
<a href="#process-the-protein-data" class="anchor"></a>Process the protein data</h1>
<p>The protein data is processed in three steps: normalization, imputation (using the KNN algorithm) and batch correction (using the <code>ComBat</code> algorithm).</p>
<div id="normalization-1" class="section level2">
<h2 class="hasAnchor">
<a href="#normalization-1" class="anchor"></a>Normalization</h2>
<p>Normalization is performed similarly to peptide normalization. We use the same functions, but since the data were log-transformed at the peptide level, we subtract by the statistic (median or mean) instead of dividing.</p>
<div class="sourceCode" id="cb102"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">%&gt;%</span>
    <span class="co">## Center columns with median</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">sweep</a></span><span class="op">(</span>i <span class="op">=</span> <span class="st">"proteins"</span>,
          MARGIN <span class="op">=</span> <span class="fl">2</span>,
          FUN <span class="op">=</span> <span class="st">"-"</span>,
          STATS <span class="op">=</span> <span class="fu">colMedians</span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">.</span><span class="op">[[</span><span class="st">"proteins"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,
                             na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
          name <span class="op">=</span> <span class="st">"proteins_norm1"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Center rows with mean</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">sweep</a></span><span class="op">(</span>i <span class="op">=</span> <span class="st">"proteins_norm1"</span>,
          MARGIN <span class="op">=</span> <span class="fl">1</span>,
          FUN <span class="op">=</span> <span class="st">"-"</span>,
          STATS <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowMeans</a></span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">.</span><span class="op">[[</span><span class="st">"proteins_norm1"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,
                           na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
          name <span class="op">=</span> <span class="st">"proteins_norm2"</span><span class="op">)</span> <span class="op">-&gt;</span>
    <span class="va">scp</span></code></pre></div>
</div>
<div id="imputation" class="section level2">
<h2 class="hasAnchor">
<a href="#imputation" class="anchor"></a>Imputation</h2>
<p>The protein data contains a lot of missing values. The graph below shows the distribution of the proportion missingness in cells. Cells contain on average over 75 % missing values!</p>
<div class="sourceCode" id="cb103"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-class.html">longFormat</a></span><span class="op">(</span><span class="va">scp</span><span class="op">[</span>, , <span class="st">"proteins_norm2"</span><span class="op">]</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="fu">group_by</span><span class="op">(</span><span class="va">colname</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">summarize</span><span class="op">(</span>missingness <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">value</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">missingness</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: 'experiments' dropped; see 'metadata'</code></pre>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-29-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>The missing data is imputed using K nearest neighbors. The SCoPE2 script runs KNN with k = 3. We made a wrapper around the author’s code to apply imputation to our <code>QFeatures</code> object.</p>
<div class="sourceCode" id="cb105"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/scp_imputeKNN.html">scp_imputeKNN</a></span><span class="op">(</span><span class="va">scp</span>,
                     i <span class="op">=</span> <span class="st">"proteins_norm2"</span>,
                     name <span class="op">=</span> <span class="st">"proteins_impd"</span>,
                     k <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></code></pre></div>
<p><code>QFeatures</code> also provides KNN imputation by calling to the <code><a href="https://rdrr.io/pkg/impute/man/impute.knn.html">impute::impute.knn</a></code> function. However, the implementation is different in the sense that SCoPE2 performs KNN imputation in the sample space, meaning that data from neighbouring cells are used to impute, whereas <code><a href="https://rdrr.io/pkg/impute/man/impute.knn.html">impute::impute.knn</a></code> performs KNN imputation in the gene space, meaning that data from neighbouring genes are used to impute the missing values. We provide the code for KNN imputation with <code>QFeatures</code> but do not run in order to reproduce the SCoPE2 analysis.</p>
<div class="sourceCode" id="cb106"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/impute.html">impute</a></span><span class="op">(</span><span class="va">scp</span>,
              i <span class="op">=</span> <span class="st">"proteins_norm2"</span>,
              method <span class="op">=</span> <span class="st">"knn"</span>,
              k <span class="op">=</span> <span class="fl">3</span>, rowmax <span class="op">=</span> <span class="fl">1</span>, colmax<span class="op">=</span> <span class="fl">1</span>,
              maxp <span class="op">=</span> <span class="cn">Inf</span>, rng.seed <span class="op">=</span> <span class="fl">1234</span><span class="op">)</span></code></pre></div>
</div>
<div id="batch-correction" class="section level2">
<h2 class="hasAnchor">
<a href="#batch-correction" class="anchor"></a>Batch correction</h2>
<p>The final step is to model the remaining batch effects and correct for it. The data were acquired as a series of MS runs. Recall we had 177 assays at the beginning of the workflow. Each MS run can be subjected to small technical perturbations that lead to differences in the data. This can be corrected to avoid attributing biological effects to technical effects. The <code>ComBat</code> algorithm (<span class="citation">Johnson, Li, and Rabinovic (2007)</span>) is used in the SCoPE2 script to correct for those batch effects. <code>ComBat</code> is part of the <code>sva</code> package. It requires a batch variable, in this case the LC-MS/MS run, and adjusts for batch effects, while protecting variables of interest, the sample type in this case. All the information is contained in the <code>colData</code> of the <code>QFeatures</code> object. We first extract the assays with the associate <code>colData</code>.</p>
<div class="sourceCode" id="cb107"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu">getWithColData</span><span class="op">(</span><span class="va">scp</span>, <span class="st">"proteins_impd"</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: 'experiments' dropped; see 'metadata'</code></pre>
<pre><code>## harmonizing input:
##   removing 16489 sampleMap rows not in names(experiments)</code></pre>
<p>We next store the batch variable and create the design matrix. We then call the functions and overwrite the data matrix. Recall the data matrix can be accessed using the <code>assay</code> function. Note also that we here use <code>ComBatv3.34</code> that was loaded at the beginning of the vignette (not shown). This function was taken from an older version of the <code>sva</code> package (version <code>3.34.0</code>). This is to replicate the SCoPE2 results. More recent versions have implemented a check for within-batch invariant proteins that will ignore batch correction for a protein if at least one of the batch contain constant values.</p>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">batch</span> <span class="op">&lt;-</span> <span class="fu">colData</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">$</span><span class="va">Set</span>
<span class="va">model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span><span class="op">~</span> <span class="va">SampleType</span>, data <span class="op">=</span> <span class="fu">colData</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">)</span>
<span class="fu">assay</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/ComBatv3.34.html">ComBatv3.34</a></span><span class="op">(</span>dat <span class="op">=</span> <span class="fu">assay</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span>,
                          batch <span class="op">=</span> <span class="va">batch</span>,
                          mod <span class="op">=</span> <span class="va">model</span><span class="op">)</span></code></pre></div>
<p>Finally, we add the batch corrected assay to the <code>QFeatures</code> object and create the feature links.</p>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-class.html">addAssay</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">sce</span>,
             name <span class="op">=</span> <span class="st">"proteins_batchC"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/AssayLinks.html">addAssayLinkOneToOne</a></span><span class="op">(</span>from <span class="op">=</span> <span class="st">"proteins_impd"</span>,
                         to <span class="op">=</span> <span class="st">"proteins_batchC"</span><span class="op">)</span> <span class="op">-&gt;</span>
    <span class="va">scp</span></code></pre></div>
</div>
<div id="the-scope2-protein-data" class="section level2">
<h2 class="hasAnchor">
<a href="#the-scope2-protein-data" class="anchor"></a>The SCoPE2 protein data</h2>
<p>Before exporting the data as <code>Proteins-processed.csv</code>, the authors performed an additional normalization step.</p>
<div class="sourceCode" id="cb112"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">%&gt;%</span>
    <span class="co">## Center columns with median</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">sweep</a></span><span class="op">(</span>i <span class="op">=</span> <span class="st">"proteins_batchC"</span>,
          MARGIN <span class="op">=</span> <span class="fl">2</span>,
          FUN <span class="op">=</span> <span class="st">"-"</span>,
          STATS <span class="op">=</span> <span class="fu">colMedians</span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">.</span><span class="op">[[</span><span class="st">"proteins_batchC"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,
                             na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
          name <span class="op">=</span> <span class="st">"proteins_batchC_norm1"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Center rows with mean</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-processing.html">sweep</a></span><span class="op">(</span>i <span class="op">=</span> <span class="st">"proteins_batchC_norm1"</span>,
          MARGIN <span class="op">=</span> <span class="fl">1</span>,
          FUN <span class="op">=</span> <span class="st">"-"</span>,
          STATS <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowMeans</a></span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">.</span><span class="op">[[</span><span class="st">"proteins_batchC_norm1"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,
                           na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
          name <span class="op">=</span> <span class="st">"proteins_scp"</span><span class="op">)</span> <span class="op">-&gt;</span>
    <span class="va">scp</span></code></pre></div>
<p>We named the last assay <code>proteins_scp</code>. We will contrast this data matrix to <code>proteins_SCoPE2</code> later in the next section to assess the fidelity of the replication.</p>
</div>
</div>
<div id="benchmarking-the-replication" class="section level1">
<h1 class="hasAnchor">
<a href="#benchmarking-the-replication" class="anchor"></a>Benchmarking the replication</h1>
<p>We will now compare the data that were provided by Specht and colleagues with the data generated in this vignette. We compare the peptide and the protein data.</p>
<div id="compare-the-selected-cells" class="section level2">
<h2 class="hasAnchor">
<a href="#compare-the-selected-cells" class="anchor"></a>Compare the selected cells</h2>
<p>One of the above section filtered the single cells based on the median coefficient of variation per cell. We will check that we could indeed reproduce the SCoPE2 cell filter. Note that the peptide and protein data contain the same set of cells.</p>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-37-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>The <code>scp</code> filtering step keep 9 additional cells (0.6 % out of all cells) compared to SCoPE2.</p>
</div>
<div id="compare-peptide-data" class="section level2">
<h2 class="hasAnchor">
<a href="#compare-peptide-data" class="anchor"></a>Compare peptide data</h2>
<p>The SCoPE2 and the <code>scp</code> peptide data have comparable dimensions, although they are not exactly the same. Our workflow kept 10 additional peptides out of 9364. Similarly to the filtered cells, this difference is negligible and demonstrate an almost perfect replication of the filtering steps.</p>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-38-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>To assess the difference between the data matrices, we intersect the peptides and the cells to have comparable matrices. The range of the differences between the 2 datasets is contained in -0.2 and 0.2, with a very sharp . This corresponds to approximately 2 % of the total range of the data (-8.941, 6.166). Therefore, we can say that the <code>scp</code> workflow could accurately replicate the SCoPE2 peptide data.</p>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-39-1.png" width="70%" style="display: block; margin: auto;"></p>
</div>
<div id="compare-protein-data" class="section level2">
<h2 class="hasAnchor">
<a href="#compare-protein-data" class="anchor"></a>Compare protein data</h2>
<p>Similarly to the peptide data, the SCoPE2 and the <code>scp</code> protein data contain different but highly overlapping (99.28 %) sets of proteins. It is expected to see more proteins in the <code>scp</code> results with respect to <code>SCoPE2</code> because this was already seen for the peptide data. However, some proteins are only found in SCoPE2. This is a consequence of the remapping of peptides to proteins that occurred when joining together all the peptides assays in one. This step was required by <code>scp</code> to properly aggregate peptides to proteins, but was not considered in the SCoPE2 workflow.</p>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-40-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>The range of differences between SCoPE2 and <code>scp</code> is much wider for the protein data than for the peptide data. The range of the differences between the <code>scp</code> and the SCoPE2 data is (-3.06, 2.66) and this comparable to the range of the SCoPE2 protein expression values. However, 99 % of the differences are lying in (-0.45, 0.82) and there is a sharp peak around 0. This indicates that the small differences observed at peptide level have propagated during protein imputation, batch correction and normalization. This is problematic as it indicates that at least one of those steps is unstable. We will the batch correction and the data imputation in a later section.</p>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-41-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>To summarize, here is an overview of the differences between our results using <code>scp</code> and the expected results obtained by the <code>SCoPE2</code> authors.</p>
<div class="sourceCode" id="cb113"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cell_sel</span> <span class="op">+</span>
    <span class="va">peptide_sel</span> <span class="op">+</span>
    <span class="va">protein_sel</span> <span class="op">+</span>
    <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_spacer.html">plot_spacer</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="va">peptide_diff</span> <span class="op">+</span>
    <span class="va">protein_diff</span> <span class="op">+</span>
    <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_layout.html">plot_layout</a></span><span class="op">(</span>ncol <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></code></pre></div>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-42-1.png" width="70%" style="display: block; margin: auto;"></p>
</div>
<div id="pca" class="section level2">
<h2 class="hasAnchor">
<a href="#pca" class="anchor"></a>PCA</h2>
<p>To assess the separability between macrophages and monocytes, Specht and colleagues perform weighted principal component analysis (PCA) on the protein data. The weights are proportional to the amount of correlation between a protein and the other proteins. Computing the weighted PCA requires some manual implementation (taken from the SCoPE2 script). The authors use the expression matrix as input. We can easily get this matrix from the desired assay.</p>
<div class="sourceCode" id="cb114"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Extract the protein expression matrix</span>
<span class="va">X</span> <span class="op">&lt;-</span> <span class="fu">assay</span><span class="op">(</span><span class="va">scp</span><span class="op">[[</span><span class="st">"proteins_scp"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>
<span class="co">## Compute the weights</span>
<span class="va">w</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>
<span class="co">## Compute the PCs (code taken from the SCoPE2 script)</span>
<span class="va">Xw</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">w</span><span class="op">)</span> <span class="op">%*%</span>  <span class="va">X</span>
<span class="va">Xcor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">Xw</span><span class="op">)</span>
<span class="va">pcaRes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/eigen.html">eigen</a></span><span class="op">(</span><span class="va">Xcor</span><span class="op">)</span>
<span class="va">pcaPercentVar</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">pcaRes</span><span class="op">$</span><span class="va">values</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">pcaRes</span><span class="op">$</span><span class="va">values</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span><span class="op">)</span>
<span class="co">## Start plotting</span>
<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>PC <span class="op">=</span> <span class="va">pcaRes</span><span class="op">$</span><span class="va">vectors</span><span class="op">[</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span>,
           <span class="fu">colData</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">Xcor</span><span class="op">)</span>, <span class="op">]</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">PC.1</span>, y <span class="op">=</span> <span class="va">PC.2</span>, col <span class="op">=</span> <span class="va">SampleType</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_point</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
    <span class="co">## Annotate plot</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"PC1 ("</span>, <span class="va">pcaPercentVar</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="st">"%)"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"PC2 ("</span>, <span class="va">pcaPercentVar</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, <span class="st">"%)"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"PCA plot of the processed protein data"</span><span class="op">)</span> <span class="op">+</span>
    <span class="co">## Adapt the visual style to match the preprint figure</span>
    <span class="fu">scale_color_manual</span><span class="op">(</span>name <span class="op">=</span> <span class="st">""</span>, values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#048ABF"</span>,<span class="st">"#FF5733"</span><span class="op">)</span>,
                       labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Macrophages"</span>, <span class="st">"Monocytes"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"top"</span><span class="op">)</span></code></pre></div>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-43-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>This plot allow us to draw the same conclusion as in the original preprint: (i) macropages and monocytes are well separated and (ii) macrophages are more spread-out than monocytes. However, the plot shows notable difference with the original figure: (i) more variance is explained by the PCA on the protein data derived from this vignette and (ii) macrophages and monocytes are best separated on the second PC rather than the first.</p>
<p>As a side note, the <code>scater</code> packages provides a suite of functions that perform and visualize dimension reduction for <code>SingleCellExperiment</code> objects. Since our assays are all <code>SingleCellExperiment</code> objects, we can perform regular PCA on the protein data in just a few commands.</p>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://bioconductor.org/packages/scater/">scater</a></span><span class="op">)</span>
<span class="fu">getWithColData</span><span class="op">(</span><span class="va">scp</span>, <span class="st">"proteins_scp"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Perform PCA, see ?runPCA for more info about arguments</span>
    <span class="fu"><a href="https://rdrr.io/pkg/scater/man/runPCA.html">runPCA</a></span><span class="op">(</span>ncomponents <span class="op">=</span> <span class="fl">50</span>,
           ntop <span class="op">=</span> <span class="cn">Inf</span>,
           scale <span class="op">=</span> <span class="cn">TRUE</span>,
           exprs_values <span class="op">=</span> <span class="fl">1</span>,
           name <span class="op">=</span> <span class="st">"PCA"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Plotting is performed in a single line of code</span>
    <span class="fu"><a href="https://rdrr.io/pkg/scater/man/plot_reddim.html">plotPCA</a></span><span class="op">(</span>colour_by <span class="op">=</span> <span class="st">"SampleType"</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: 'experiments' dropped; see 'metadata'</code></pre>
<pre><code>## harmonizing input:
##   removing 20986 sampleMap rows not in names(experiments)</code></pre>
<pre><code>## Warning: Ignoring redundant column names in 'colData(x)':</code></pre>
<p><img src="SCoPE2_files/figure-html/unnamed-chunk-44-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>This plot is different from the previous plot because no weighting is considered during the second PCA.</p>
<div class="sourceCode" id="cb119"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## To remove when remainder of vignette is finished</span>
<span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## R Under development (unstable) (2021-01-19 r79847)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Manjaro Linux
## 
## Matrix products: default
## BLAS:   /usr/lib/libblas.so.3.9.0
## LAPACK: /usr/lib/liblapack.so.3.9.0
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
## [8] methods   base     
## 
## other attached packages:
##  [1] scater_1.19.9                sva_3.39.0                  
##  [3] BiocParallel_1.25.4          genefilter_1.73.1           
##  [5] mgcv_1.8-33                  nlme_3.1-151                
##  [7] patchwork_1.1.1              forcats_0.5.1               
##  [9] stringr_1.4.0                dplyr_1.0.4                 
## [11] purrr_0.3.4                  readr_1.4.0                 
## [13] tidyr_1.1.2                  tibble_3.0.6                
## [15] ggplot2_3.3.3                tidyverse_1.3.0             
## [17] SCoPE2.replication_0.1.0     scpdata_0.99.2              
## [19] ExperimentHub_1.17.1         AnnotationHub_2.23.2        
## [21] BiocFileCache_1.15.1         dbplyr_2.1.0                
## [23] scp_1.1.4                    QFeatures_1.1.1             
## [25] MultiAssayExperiment_1.17.11 SingleCellExperiment_1.13.10
## [27] SummarizedExperiment_1.21.1  Biobase_2.51.0              
## [29] GenomicRanges_1.43.3         GenomeInfoDb_1.27.6         
## [31] IRanges_2.25.6               S4Vectors_0.29.7            
## [33] BiocGenerics_0.37.1          MatrixGenerics_1.3.1        
## [35] matrixStats_0.58.0           BiocStyle_2.19.1            
## 
## loaded via a namespace (and not attached):
##   [1] readxl_1.3.1                  backports_1.2.1              
##   [3] systemfonts_1.0.1             lazyeval_0.2.2               
##   [5] splines_4.1.0                 digest_0.6.27                
##   [7] htmltools_0.5.1.1             viridis_0.5.1                
##   [9] magrittr_2.0.1                memoise_2.0.0                
##  [11] ScaledMatrix_0.99.2           limma_3.47.6                 
##  [13] Biostrings_2.59.2             annotate_1.69.0              
##  [15] modelr_0.1.8                  pkgdown_1.6.1                
##  [17] colorspace_2.0-0              blob_1.2.1                   
##  [19] rvest_0.3.6                   rappdirs_0.3.3               
##  [21] textshaping_0.3.0             haven_2.3.1                  
##  [23] xfun_0.21                     crayon_1.4.1                 
##  [25] RCurl_1.98-1.2                jsonlite_1.7.2               
##  [27] survival_3.2-7                glue_1.4.2                   
##  [29] gtable_0.3.0                  zlibbioc_1.37.0              
##  [31] XVector_0.31.1                DelayedArray_0.17.7          
##  [33] BiocSingular_1.7.2            scales_1.1.1                 
##  [35] DBI_1.1.1                     edgeR_3.33.1                 
##  [37] Rcpp_1.0.6                    viridisLite_0.3.0            
##  [39] xtable_1.8-4                  rsvd_1.0.3                   
##  [41] bit_4.0.4                     MsCoreUtils_1.3.2            
##  [43] httr_1.4.2                    ellipsis_0.3.1               
##  [45] pkgconfig_2.0.3               XML_3.99-0.5                 
##  [47] farver_2.0.3                  scuttle_1.1.15               
##  [49] locfit_1.5-9.4                tidyselect_1.1.0             
##  [51] labeling_0.4.2                rlang_0.4.10                 
##  [53] later_1.1.0.1                 AnnotationDbi_1.53.1         
##  [55] munsell_0.5.0                 BiocVersion_3.13.1           
##  [57] cellranger_1.1.0              tools_4.1.0                  
##  [59] cachem_1.0.4                  cli_2.3.0                    
##  [61] generics_0.1.0                RSQLite_2.2.3                
##  [63] broom_0.7.4                   evaluate_0.14                
##  [65] fastmap_1.1.0                 yaml_2.2.1                   
##  [67] ragg_1.1.0                    knitr_1.31                   
##  [69] bit64_4.0.5                   fs_1.5.0                     
##  [71] KEGGREST_1.31.1               AnnotationFilter_1.15.0      
##  [73] sparseMatrixStats_1.3.6       mime_0.10                    
##  [75] xml2_1.3.2                    compiler_4.1.0               
##  [77] rstudioapi_0.13               beeswarm_0.2.3               
##  [79] filelock_1.0.2                curl_4.3                     
##  [81] png_0.1-7                     interactiveDisplayBase_1.29.0
##  [83] reprex_1.0.0                  stringi_1.5.3                
##  [85] highr_0.8                     ps_1.5.0                     
##  [87] desc_1.2.0                    lattice_0.20-41              
##  [89] ProtGenerics_1.23.7           Matrix_1.3-2                 
##  [91] vctrs_0.3.6                   pillar_1.4.7                 
##  [93] lifecycle_1.0.0               BiocManager_1.30.10          
##  [95] BiocNeighbors_1.9.4           irlba_2.3.3                  
##  [97] bitops_1.0-6                  httpuv_1.5.5                 
##  [99] R6_2.5.0                      bookdown_0.21                
## [101] promises_1.2.0.1              gridExtra_2.3                
## [103] vipor_0.4.5                   MASS_7.3-53                  
## [105] assertthat_0.2.1              rprojroot_2.0.2              
## [107] withr_2.4.1                   GenomeInfoDbData_1.2.4       
## [109] hms_1.0.0                     beachmat_2.7.6               
## [111] grid_4.1.0                    rmarkdown_2.6                
## [113] DelayedMatrixStats_1.13.5     shiny_1.6.0                  
## [115] lubridate_1.7.9.2             ggbeeswarm_0.6.0</code></pre>
<div class="sourceCode" id="cb121"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">knitr</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/knitr/man/opts_chunk.html">opts_chunk</a></span><span class="op">$</span><span class="fu">set</span><span class="op">(</span>eval <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="further-data-exploration" class="section level1">
<h1 class="hasAnchor">
<a href="#further-data-exploration" class="anchor"></a>Further data exploration</h1>
<p>In this section we want to extend the discussion on some key aspects of the data.</p>
<div id="qfeatures-plot" class="section level2">
<h2 class="hasAnchor">
<a href="#qfeatures-plot" class="anchor"></a><code>QFeatures</code> plot</h2>
<p>The <code>QFeatures</code> plot shows the quantitative data for a features at the different expression levels. For instance, suppose we are interested in the protein <em>VIM</em> (protein ID is <code>P08670</code>) from one of the SCoPE2 batches (<em>e.g.</em> <code>191110S_LCB7_X_APNOV16plex2_Set_9</code>). A useful QC is to monitor the data processing at the PSM, peptide and protein level. This can easily be done thanks to the <code>QFeatures</code> framework. Using the <code>subsetByAssay</code> and the <code>subsetByRow</code> functions, we can extract the batch and feature of interest, respectively. Then, the data is formated to a long format table that can easily be plugged in the <code>ggplot2</code> visualization tool.</p>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">%&gt;%</span>
    <span class="co">## Get the features related to VIM (P08670)</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-subsetBy.html">subsetByFeature</a></span><span class="op">(</span><span class="st">"P08670"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Format the `QFeatures` to a long format table</span>
    <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-class.html">longFormat</a></span><span class="op">(</span>colDataCols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Set"</span>, <span class="st">"SampleType"</span>, <span class="st">"Channel"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="co">## Keep only the SCoPE2 set of interest</span>
    <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">Set</span> <span class="op">==</span> <span class="st">"191110S_LCB7_X_APNOV16plex2_Set_9"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">eez</span>
    <span class="va">tmp</span> <span class="op">%&gt;%</span>
    <span class="co">## This is used to preserve ordering of the samples and assays in ggplot2</span>
    <span class="fu">mutate</span><span class="op">(</span>assay <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">assay</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">)</span>,
           Channel <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">sub</a></span><span class="op">(</span><span class="st">"RI"</span>, <span class="st">"TMT-"</span>, <span class="va">Channel</span><span class="op">)</span>,
           Channel <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Channel</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">Channel</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Start plotting</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Channel</span>, y <span class="op">=</span> <span class="va">value</span>, group <span class="op">=</span> <span class="va">rowname</span>, col <span class="op">=</span> <span class="va">SampleType</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="co">## Plot every assay in a separate facet</span>
    <span class="fu">facet_wrap</span><span class="op">(</span>facets <span class="op">=</span> <span class="fu">vars</span><span class="op">(</span><span class="va">assay</span><span class="op">)</span>, scales <span class="op">=</span> <span class="st">"free_y"</span><span class="op">)</span> <span class="op">+</span>
    <span class="co">## Annotate plot</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"Channels"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="st">"Intensity (arbitrary units)"</span><span class="op">)</span> <span class="op">+</span>
    <span class="co">## Improve plot aspect</span>
    <span class="fu">theme</span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">90</span><span class="op">)</span>,
          strip.text <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>hjust <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>,
          legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></code></pre></div>
<p>This graph can help us track the processing of the data.</p>
<p>In later pipelines, we could imagine propagating the peptide variability to the protein level when performing differential expression analysis. This is has already been suggested see for instance <span class="citation">Sticker et al. (2019)</span>, and we believe that our framework will facilitate the development and benchmarking of such methodologies on MS-SCP data.</p>
<p>Another solution readily available from the <code>QFeatures</code> package is to apply more suitable methods such as robust summary as an aggregation function. We experiment this here. We will aggregate again the peptide data</p>
<div class="sourceCode" id="cb123"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-aggregate.html">aggregateFeatures</a></span><span class="op">(</span><span class="va">scp</span>,
                         i <span class="op">=</span> <span class="st">"peptides_log"</span>,
                         name <span class="op">=</span> <span class="st">"proteins_robSum"</span>,
                         fcol <span class="op">=</span> <span class="st">"protein"</span>,
                         fun <span class="op">=</span> <span class="fu">MsCoreUtils</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/MsCoreUtils/man/robustSummary.html">robustSummary</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-aggregate.html">aggregateFeatures</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/scpdata/man/specht2019v3.html">specht2019v3</a></span><span class="op">(</span><span class="op">)</span>,
                  i <span class="op">=</span> <span class="st">"peptides"</span>,
                  name <span class="op">=</span> <span class="st">"proteins_rs"</span>,
                  fcol <span class="op">=</span> <span class="st">"protein"</span>,
                  fun <span class="op">=</span> <span class="fu">MsCoreUtils</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/MsCoreUtils/man/robustSummary.html">robustSummary</a></span><span class="op">)</span></code></pre></div>
</div>
<div id="batch-effect" class="section level2">
<h2 class="hasAnchor">
<a href="#batch-effect" class="anchor"></a>Batch effect</h2>
<p>The SCoPE2 dataset has been acquired in 177 different MS batches. These batches were either acquired using a TMT-11 or a TMT-16 protocol. Furthermore, the MS batches were distributed over 4 chromatographic batches. Acquiring data in different batches is technically inevitable and requires to correct for it computationally. We show here the batch effects present at the peptide level after log-transformation, but before normalization, imputation and batch correction. We apply the NIPALS algorithm to account for missing data.</p>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">nipals</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">GGally</span><span class="op">)</span>
<span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu">getWithColData</span><span class="op">(</span><span class="va">scp</span>, <span class="st">"peptides_log"</span><span class="op">)</span>
<span class="va">pcaRes</span> <span class="op">&lt;-</span> <span class="fu">nipals</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span><span class="op">)</span>,
                 ncomp <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>
<span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu">colData</span><span class="op">(</span><span class="va">sce</span><span class="op">)</span>,
                 <span class="va">pcaRes</span><span class="op">$</span><span class="va">scores</span><span class="op">)</span></code></pre></div>
<p>We first check the amount of variance explained by the 5 first components. From the graph below, we can see that almost 20 % of the variance is explained by the first 2 components, but the remaining components still capture a significant proportion of the variance.</p>
<div class="sourceCode" id="cb125"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>PC <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"PC"</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">5</span><span class="op">)</span>, ev <span class="op">=</span> <span class="va">pcaRes</span><span class="op">$</span><span class="va">R2</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">PC</span>,
        y <span class="op">=</span> <span class="va">ev</span> <span class="op">*</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_bar</span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"identity"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="st">"Explained variance (%)"</span><span class="op">)</span></code></pre></div>
<p>Let’s first look at the batch effect on the first 5 components. This is a overview of the PCA results:</p>
<div class="sourceCode" id="cb126"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df</span> <span class="op">%&gt;%</span>
    <span class="fu">ggpairs</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>color <span class="op">=</span> <span class="va">lcbatch</span>,
                alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span>,
            columns <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"PC"</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">5</span><span class="op">)</span>,
            legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></code></pre></div>
<p>The chromatographic batches are perfectly separated in the first two components:</p>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">PC1</span>,
        y <span class="op">=</span> <span class="va">PC2</span>,
        col <span class="op">=</span> <span class="va">lcbatch</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></code></pre></div>
<p>In the two next components, the batches are no more separated and the biological variation seems to captured:</p>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">PC3</span>,
        y <span class="op">=</span> <span class="va">PC4</span>,
        col <span class="op">=</span> <span class="va">lcbatch</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span> <span class="op">+</span>
    <span class="va">df</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">PC3</span>,
        y <span class="op">=</span> <span class="va">PC4</span>,
        col <span class="op">=</span> <span class="va">SampleType</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></code></pre></div>
<p>So this means that monocytes and macrophages effect we saw in the PCA</p>
</div>
<div id="missingness" class="section level2">
<h2 class="hasAnchor">
<a href="#missingness" class="anchor"></a>Missingness</h2>
<div id="technical-missingness" class="section level3">
<h3 class="hasAnchor">
<a href="#technical-missingness" class="anchor"></a>Technical missingness</h3>
<div class="sourceCode" id="cb129"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">peptides</span> <span class="op">&lt;-</span> <span class="va">scp</span><span class="op">[[</span><span class="st">"peptides"</span><span class="op">]</span><span class="op">]</span>
<span class="va">nNaRes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-missing-data.html">nNA</a></span><span class="op">(</span><span class="va">peptides</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nNaRes</span><span class="op">$</span><span class="va">nNAcols</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu">colData</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">pNA</span>,
        fill <span class="op">=</span> <span class="va">lcbatch</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_density</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"Percentage missingness (%)"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Missingness per cell"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb131"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">scp</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/countUniqueFeatures.html">countUniqueFeatures</a></span><span class="op">(</span><span class="va">scp</span>,
                           i <span class="op">=</span> <span class="st">"peptides_log"</span>,
                           rowDataCol <span class="op">=</span> <span class="st">"protein"</span>,
                           varName <span class="op">=</span> <span class="st">"ProteinCounts"</span><span class="op">)</span>
<span class="fu">colData</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">ProteinCounts</span>,
        fill <span class="op">=</span> <span class="va">lcbatch</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">facet_grid</span><span class="op">(</span>rows <span class="op">=</span> <span class="fu">vars</span><span class="op">(</span><span class="va">lcbatch</span><span class="op">)</span>, scales <span class="op">=</span> <span class="st">"free_y"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"Protein count"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="st">"Cell count"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb132"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nNaRes</span><span class="op">$</span><span class="va">nNArows</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu">rowData</span><span class="op">(</span><span class="va">peptides</span><span class="op">)</span><span class="op">[</span><span class="va">nNaRes</span><span class="op">$</span><span class="va">nNArows</span><span class="op">$</span><span class="va">name</span>, <span class="op">]</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">mutate</span><span class="op">(</span>Median <span class="op">=</span> <span class="fu">rowMedians</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log2</a></span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">peptides</span><span class="op">)</span><span class="op">[</span><span class="va">nNaRes</span><span class="op">$</span><span class="va">nNArows</span><span class="op">$</span><span class="va">name</span>, <span class="op">]</span><span class="op">)</span>,
                           na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Median</span>,
        y <span class="op">=</span> <span class="va">pNA</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">stat_density2d</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>fill <span class="op">=</span> <span class="va">..density..</span><span class="op">^</span><span class="fl">0.1</span><span class="op">)</span>,
                   geom <span class="op">=</span> <span class="st">"tile"</span>,
                   contour <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_fill_gradientn</span><span class="op">(</span>colours <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/colorRamp.html">colorRampPalette</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"white"</span>, <span class="va">blues9</span><span class="op">)</span><span class="op">)</span><span class="op">(</span><span class="fl">256</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span>,
          panel.background <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
          panel.grid.major <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
          panel.grid.minor <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
          panel.border <span class="op">=</span> <span class="fu">element_rect</span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"black"</span>, fill <span class="op">=</span> <span class="cn">NA</span>, size <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="st">"Percentage missingness (%)"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"log median expression"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Missingness per peptide"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb133"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">proteins</span> <span class="op">&lt;-</span> <span class="va">scp</span><span class="op">[[</span><span class="st">"proteins"</span><span class="op">]</span><span class="op">]</span>
<span class="va">mat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">0</span>,
              nrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">proteins</span><span class="op">)</span>,
              ncol <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="fu">colData</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">$</span><span class="va">Set</span><span class="op">)</span><span class="op">)</span>,
              dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">proteins</span><span class="op">)</span>,
                              <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="fu">colData</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">$</span><span class="va">Set</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="kw">for</span> <span class="op">(</span><span class="va">batch</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="fu">colData</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">$</span><span class="va">Set</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
   <span class="va">x</span> <span class="op">&lt;-</span> <span class="fu">assay</span><span class="op">(</span><span class="va">proteins</span><span class="op">)</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="fu">colData</span><span class="op">(</span><span class="va">scp</span><span class="op">)</span><span class="op">[</span><span class="va">scp</span><span class="op">$</span><span class="va">Set</span> <span class="op">==</span> <span class="va">batch</span>, <span class="op">]</span><span class="op">)</span><span class="op">]</span>
   <span class="va">mat</span><span class="op">[</span>, <span class="va">batch</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="op">&lt;</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span>
<span class="op">}</span>
<span class="va">res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">mat</span><span class="op">)</span>
<span class="va">res</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"Amount of batches"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Distribution of the number of proteins in batches"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/QFeatures-class.html">longFormat</a></span><span class="op">(</span><span class="va">proteins</span><span class="op">)</span>
<span class="va">lf</span> <span class="op">%&gt;%</span>
    <span class="fu">mutate</span><span class="op">(</span>rowname <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">rowname</span>,
                            levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="va">res</span>, decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="va">data.frame</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="va">rowname</span>,
        x <span class="op">=</span> <span class="va">colname</span>,
        fill <span class="op">=</span> <span class="va">value</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_tile</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_fill_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"log expression"</span>,
                          na.value <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>axis.text <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"Single cells"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="st">"Proteins"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Protein expression matrix"</span><span class="op">)</span>

<span class="fu">assay</span><span class="op">(</span><span class="va">proteins</span><span class="op">)</span><span class="op">[</span>, <span class="op">]</span> <span class="op">%&gt;%</span>
    <span class="va">t</span> <span class="op">%&gt;%</span>
    <span class="va">image</span></code></pre></div>
</div>
<div id="biological-missingness" class="section level3">
<h3 class="hasAnchor">
<a href="#biological-missingness" class="anchor"></a>Biological missingness</h3>
<p>We showed previously in this vignette that MS-SCP data is characterized by a high rate of missing data. This missing data can be either technical or biological. To illustrate this, we plot the rate of missingness in macrophages against the rate of missingness in monocytes. Every point in the graph represents a peptide. We color the peptide by the amount of change in expression observed between the macrophages and the monocytes.</p>
<p>The code for plotting is rather elaborate, but notice the necessary data can easily be extracted using only few commands.</p>
<div class="sourceCode" id="cb135"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sce</span> <span class="op">&lt;-</span> <span class="fu">getWithColData</span><span class="op">(</span><span class="va">scp</span>, <span class="st">"peptides_log"</span><span class="op">)</span>
<span class="co">## Extract expression data from macrophages and monocytes separately</span>
<span class="va">monoDat</span> <span class="op">&lt;-</span> <span class="fu">assay</span><span class="op">(</span><span class="va">sce</span><span class="op">[</span>, <span class="va">sce</span><span class="op">$</span><span class="va">SampleType</span> <span class="op">==</span> <span class="st">"Monocyte"</span><span class="op">]</span><span class="op">)</span>
<span class="va">m0Dat</span> <span class="op">&lt;-</span> <span class="fu">assay</span><span class="op">(</span><span class="va">sce</span><span class="op">[</span>, <span class="va">sce</span><span class="op">$</span><span class="va">SampleType</span> <span class="op">==</span> <span class="st">"Macrophage"</span><span class="op">]</span><span class="op">)</span>
<span class="co">## Create a table with the rate of missingness for each cell type and</span>
<span class="co">## compute the log fold change in median expression</span>
<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>m0Missing <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowMeans</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">m0Dat</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span>,
           monoMissing <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowMeans</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">monoDat</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span>,
           logFC <span class="op">=</span> <span class="fu">rowMedians</span><span class="op">(</span><span class="va">m0Dat</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">-</span> <span class="fu">rowMedians</span><span class="op">(</span><span class="va">monoDat</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Trim log fold change to dampen the impact of outliers</span>
    <span class="fu">mutate</span><span class="op">(</span>logFC <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">logFC</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">1</span>, <span class="fl">1</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/sign.html">sign</a></span><span class="op">(</span><span class="va">logFC</span><span class="op">)</span>, <span class="va">logFC</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="co">## Start plotting</span>
    <span class="va">ggplot</span> <span class="op">-&gt;</span>
    <span class="va">p</span>
<span class="va">p</span> <span class="op">+</span>
    <span class="co">## Plot rate of missingness in macrophages</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">m0Missing</span><span class="op">)</span>, bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>axis.title.x <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>, axis.text.x <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
          axis.ticks.x <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_spacer.html">plot_spacer</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="va">p</span> <span class="op">+</span>
    <span class="co">## Plot missingness in macrophages vs missingness in monocytes</span>
    <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">m0Missing</span>, y <span class="op">=</span> <span class="va">monoMissing</span>, col <span class="op">=</span> <span class="va">logFC</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_abline</span><span class="op">(</span>slope <span class="op">=</span> <span class="fl">1</span>, intercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"grey30"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"Missingness (%) in macrophages"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="st">"Missingness (%) in monocytes"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_color_gradient2</span><span class="op">(</span>low <span class="op">=</span> <span class="st">"#048ABF"</span>, mid <span class="op">=</span> <span class="st">"bisque2"</span>, high <span class="op">=</span> <span class="st">"#FF5733"</span>,
                          breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>,
                          labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"monocyte"</span>, <span class="st">"macrophage"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="va">p</span> <span class="op">+</span>
    <span class="co">## Plot rate of missingness in monocytes</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="va">monoMissing</span><span class="op">)</span>, bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>axis.title.y <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>, axis.text.y <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
          axis.ticks.y <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
          axis.text.x <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>angle <span class="op">=</span> <span class="op">-</span><span class="fl">90</span>, vjust <span class="op">=</span> <span class="fl">0.5</span>, hjust<span class="op">=</span><span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="co">## Adjust plotting layout</span>
    <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_layout.html">plot_layout</a></span><span class="op">(</span>widths <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.85</span>, <span class="fl">0.15</span><span class="op">)</span>, heights <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.15</span>, <span class="fl">0.85</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>We can see that most of the peptides have equal missingness in macrophages and monocytes. This is expected for technical missingness and this is further confirmed by the fact that that the slope 1 line is dominated by peptides with no large difference in log fold change (pale yellow). Interestingly, we can also observe that the missingness for some peptides can be explained by biological processes that are specific to one or the other cell type. Peptides more expressed in macrophages (red) tend to be less missing in monocytes. Conversely, peptides more expressed in monocytes tend to be less missing in monocytes.</p>
</div>
<div id="imputation-issues" class="section level3">
<h3 class="hasAnchor">
<a href="#imputation-issues" class="anchor"></a>Imputation issues</h3>
<div class="sourceCode" id="cb136"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">prots</span> <span class="op">&lt;-</span> <span class="fu">getWithColData</span><span class="op">(</span><span class="va">scp</span>, <span class="st">"proteins_impd"</span><span class="op">)</span>
<span class="va">nbIdentical</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="fu">assay</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span>,
                     <span class="fl">1</span>,
                     <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="co">## Top 1</span>
<span class="va">sel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">nbIdentical</span>, decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>
<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>exprs <span class="op">=</span> <span class="fu">assay</span><span class="op">(</span><span class="va">scp</span><span class="op">[[</span><span class="st">"proteins_norm2"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">[</span><span class="va">sel</span>, <span class="op">]</span>,
           colnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">prots</span><span class="op">)</span>,
           <span class="fu">colData</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">colnames</span>,
        col <span class="op">=</span> <span class="va">SampleType</span>,
        y <span class="op">=</span> <span class="va">exprs</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_point</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="st">"log expression"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">""</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span>,
          axis.ticks.x <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
          axis.text.x <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_spacer.html">plot_spacer</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>`PCDH8: Highly missing` <span class="op">=</span> <span class="fu">assay</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span><span class="op">[</span><span class="st">"O95206"</span>, <span class="op">]</span>, <span class="co">## PCDH8</span>
           `VIM: Not missing` <span class="op">=</span> <span class="fu">assay</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span><span class="op">[</span><span class="st">"P08670"</span>, <span class="op">]</span>, <span class="co">## VIM</span>
           colnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">prots</span><span class="op">)</span>,
           <span class="fu">colData</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span>,
           check.names <span class="op">=</span> <span class="cn">FALSE</span> <span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">pivot_longer</span><span class="op">(</span>cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"PCDH8: Highly missing"</span>, <span class="st">"VIM: Not missing"</span><span class="op">)</span>,
                 names_to <span class="op">=</span> <span class="st">"type"</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">colnames</span>,
        col <span class="op">=</span> <span class="va">SampleType</span>,
        y <span class="op">=</span> <span class="va">value</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_point</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span> <span class="va">type</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">ylab</span><span class="op">(</span><span class="st">"Imputed log expression"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">xlab</span><span class="op">(</span><span class="st">"Single cell"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span>,
          axis.ticks.x <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,
          axis.text.x <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_layout.html">plot_layout</a></span><span class="op">(</span>design <span class="op">=</span> <span class="st">"12\n33"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb137"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>exprs <span class="op">=</span> <span class="fu">assay</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span><span class="op">[</span><span class="st">"O95206"</span>, <span class="op">]</span>, <span class="co">## PCDH8</span>
           colnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">prots</span><span class="op">)</span>,
           <span class="fu">colData</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">exprs</span>,
        col <span class="op">=</span> <span class="va">SampleType</span>,
        fill <span class="op">=</span> <span class="va">SampleType</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_density</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu">assay</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span><span class="op">[</span><span class="st">"O95206"</span>, <span class="va">prots</span><span class="op">$</span><span class="va">SampleType</span> <span class="op">==</span> <span class="st">"Macrophage"</span><span class="op">]</span>,
       y <span class="op">=</span> <span class="fu">assay</span><span class="op">(</span><span class="va">prots</span><span class="op">)</span><span class="op">[</span><span class="st">"O95206"</span>, <span class="va">prots</span><span class="op">$</span><span class="va">SampleType</span> <span class="op">==</span> <span class="st">"Monocyte"</span><span class="op">]</span><span class="op">)</span></code></pre></div>
</div>
</div>
</div>
<div id="conclusion" class="section level1">
<h1 class="hasAnchor">
<a href="#conclusion" class="anchor"></a>Conclusion</h1>
<p>This vignette demonstrates the standardization of the SCoPE2 data processing by the <code>scp</code> and <code>QFeatures</code> package. We demonstrate the</p>
</div>
<div id="requirements" class="section level1">
<h1 class="hasAnchor">
<a href="#requirements" class="anchor"></a>Requirements</h1>
<div id="hardware-and-timing" class="section level3">
<h3 class="hasAnchor">
<a href="#hardware-and-timing" class="anchor"></a>Hardware and timing</h3>
<p>This vignettte is compiled on a Lenovo YOGA 710-14IKB with Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 units) and 8GB of RAM and 8GB of SWAP memory.</p>
<p>The total time required to compile this vignette is:</p>
<p>The final <code>specht2019v1</code> dataset size is:</p>
</div>
<div id="session-info" class="section level3">
<h3 class="hasAnchor">
<a href="#session-info" class="anchor"></a>Session info</h3>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="reference" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#reference" class="anchor"></a>Reference</h1>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Chen2019-uc" class="csl-entry">
<p>Chen, Albert Tian, Alexander Franks, and Nikolai Slavov. 2019. <span>“<span>DART-ID</span> Increases Single-Cell Proteome Coverage.”</span> <em>PLoS Comput. Biol.</em> 15 (7): e1007082.</p>
</div>
<div id="ref-Johnson2007-nc" class="csl-entry">
<p>Johnson, W Evan, Cheng Li, and Ariel Rabinovic. 2007. <span>“Adjusting Batch Effects in Microarray Expression Data Using Empirical Bayes Methods.”</span> <em>Biostatistics</em> 8 (1): 118–27.</p>
</div>
<div id="ref-Kall2008-hb" class="csl-entry">
<p>Käll, Lukas, John D Storey, Michael J MacCoss, and William Stafford Noble. 2008. <span>“Posterior Error Probabilities and False Discovery Rates: Two Sides of the Same Coin.”</span> <em>J. Proteome Res.</em> 7 (1): 40–44.</p>
</div>
<div id="ref-Specht2019-jm" class="csl-entry">
<p>Specht, Harrison, Edward Emmott, Toni Koller, and Nikolai Slavov. 2019. <span>“High-Throughput Single-Cell Proteomics Quantifies the Emergence of Macrophage Heterogeneity.”</span> <em>bioRxiv</em>.</p>
</div>
<div id="ref-Sticker2019-gd" class="csl-entry">
<p>Sticker, Adriaan, Ludger Goeminne, Lennart Martens, and Lieven Clement. 2019. <span>“Robust Summarization and Inference in Proteome-Wide Label-Free Quantification.”</span> <em>bioRxiv</em>.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p><a href="mailto:christophe.vanderaa@uclouvain.be" class="email">christophe.vanderaa@uclouvain.be</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Christophe Vanderaa, Laurent Gatto.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
